name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 2.1.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0
  meta: ^1.2.3

dev_dependencies:
  build_runner: 1.10.0
  effective_dart: ^1.3.0
  freezed: ^0.12.2
  json_serializable: ^3.5.0
  mockito: ^4.1.3
  nock: ^1.1.2
  test: ^1.15.5
  test_coverage: ^0.5.0