name: flusmic_ui
description: A collection of widgets, utilities and extensions to integrate Flusmic more easy in Flutter.
version: 3.2.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  common_bloc: ^4.2.2
  extended_image: ^6.2.1
  flusmic: ^3.2.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  state_notifier: ^0.7.2+1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  #
