name: flusmic_ui
description: A collection of widgets, utilities and extensions to integrate Flusmic more easy in Flutter.
version: 3.1.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  common_bloc: ^4.2.0
  extended_image: ^5.1.2
  flusmic: ^3.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3
  state_notifier: ^0.7.1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0

flutter:
  #
