name: flusmic_ui
description: A collection of widgets, utilities and extensions to integrate Flusmic more easy in Flutter.
version: 4.0.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  common_bloc: ^4.2.4
  extended_image: ^7.0.2
  flusmic: ^4.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  state_notifier: ^0.7.2+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  #
